apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: argocd
type: Opaque
data:
  credentials.json: |
    {
      "AccountTag": "${CLOUDFLARE_ACCOUNT_TAG}",
      "TunnelSecret": "l7s0tsOfsM0NVA1pu5XE/EeoMsUXEWmJM23+pPQ92p0=",
      "TunnelID": "b8940426-f979-474a-bfd8-e0f8d59dcb17"
    }

