


# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  target:
    name: cloudflared-secret
    template:
      engineVersion: v2
      type: Opaque
      data:
         credentials.json: "{{ .cloudflared-credentials.json }}"
  dataFrom:
    - extract:
        key: cloudflared_homelab-tunnel
