# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  mame: argocd-clusterexternalsecret
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: argocd

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: argocd-secretstore

    target:
      name: vault-configurations
      creationPolicy: Merge
      template:
        engineVersion: v2
        data:
          AVP_TYPE: "{{ .AVP_TYPE }}"
          OP_CONNECT_TOKEN: "{{ .ACCOUNT_TOKEN }}"
          OP_CONNECT_HOST: "http://onepassword-connect.onepassword.svc.cluster.local"
    dataFrom:
      - extract:
          key: op-connect_homelab
      - extract:
          key: argocd
