---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argocd  # must be whichever namespace you installed ArgoCD to - usually 'argocd' by default
  # don't enable finalizer otherwise it'll cause a cascading delete of projects if this app is removed
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: core
  source:
    repoURL: https://github.com/chalk-hwang/home-ops.git  # keep .git suffix for GitLab, otherwise it'll 301 redirect which ArgoCD doesn't follow
    targetRevision: main
    path: argocd/projects  # relative to root of git repo so no leading slash
  destination:
    server: https://kubernetes.default.svc
    #name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false   # safe by default
