apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-configuration-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  target:
    name: vault-configuration
    template:
      engineVersion: v2
      data:
        AVP_TYPE: "{{ .AVP_TYPE }}"
        OP_CONNECT_TOKEN: "{{ .ACCESS_TOKEN }}"
        OP_CONNECT_HOST: "{{ .HOST }}"
  dataFrom:
    - extract:
        key: onepassword-connect
        property
