apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-certificate
spec:
  secretName: home-assistant-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: hass.chalk-ho.me
  dnsNames:
    - hass.chalk-ho.me
