---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  target:
    name: home-assistant-secrets
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          server_address: $INTERNAL_IPV4
          public_ip: $EXTERNAL_IPV4
  dataFrom:
    - extract:
        key: home-assistant
