---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-gitsync-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  target:
    name: home-assistant-gitsync-secrets
    template:
      engineVersion: v2
      data:
        GITSYNC_SSH_KNOWN_HOSTS_FILE: "{{ .SSH_KNOWN_HOSTS_FILE }}"
        GITSYNC_SSH_KEY_FILE: "{{ .SSH_KEY_FILE }}"
  dataFrom:
    - extract:
        key: home-assistant-gitsync
