apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant-svc
spec:
  ports:
    - name: HTTP
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: home-assistant
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-svc-vip
  labels:
    app: home-assistant
  annotations:
    kube-vip.io/vipHost: home-assistant
spec:
  ports:
    - name: ha
      port: 80
      protocol: TCP
      targetPort: 8123
  selector:
    app: home-assistant
  type: LoadBalancer
  loadBalancerIP: "10.0.7.137"
  loadBalancerClass: kube-vip.io/kube-vip-class
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-svc-tailscale
  labels:
    app: home-assistant
  annotations:
    tailscale.com/hostname: "hass"
spec:
  selector:
    app: home-assistant
  ports:
    - name: web
      port: 80
      targetPort: 8123
      protocol: TCP
  loadBalancerClass: tailscale
  type: LoadBalancer
