apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-controller-cm
data:
  TZ: "Asia/Seoul"
  JVM_MAX_THREAD_STACK_SIZE: "1300k"
  JVM_INIT_HEAP_SIZE: "800M"
  JVM_MAX_HEAP_SIZE: "1024M"
  UNIFI_HTTP_PORT: "8080"
  UNIFI_HTTPS_PORT: "8443"
  PORTAL_HTTP_PORT: "80"
  PORTAL_HTTPS_PORT: "8843"
  CERT_IS_CHAIN: "true"
  UNIFI_STDOUT: ""
  gateway.config.json: |
    {
     "protocols": {
      "bgp": {
       "64501": {
        "neighbor": {
         "10.0.7.2" : {"remote-as": "64500"},
         "10.0.7.10": {"remote-as": "64500"}
        },
        "parameters": {"router-id": "10.0.7.1"}
       }
      }
     }
    }
