---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/utilities/external-secrets/overlay
    targetRevision: main
  destination:
    namespace: external-secrets
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=false
