apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exteral-secrets
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/utilities/exteral-secrets
    targetRevision: main
  destination:
    namespace: exteral-secrets
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - Prune=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
