apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ha-cloudflare
spec:
  secretName: ha-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: hass.chalk-ho.me
  dnsNames:
  - hass.chalk-ho.me
