version: "3"
vars:
  PATH_ERROR: is not installed or correctly configured in PATH.
  CREDENTIALS_FILE: op read "op://Homelab/cloudflared_homelab-tunnel/cloudflared-credentials.json"
  TUNNEL_ID:
    sh: |
      {{ .CREDENTIALS_FILE }} | jq -r .TunnelID
  TUNNEL_SECRET:
    sh: |
      {{ .CREDENTIALS_FILE }} | jq -r .TunnelSecret
  ACCOUNT_TAG:
    sh: |
      {{ .CREDENTIALS_FILE }} | jq -r .AccountTag

silent: true

tasks:
  dns:secret:
    cmds:
      - |
        kubectl apply -f - << EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: cloudflare-secret
          namespace: cert-manager
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        stringData:
          API_TOKEN: $(op read "op://Homelab/cloudflare_chalk-ho.me/API_TOKEN")
        EOF
    ignore_error: true

  tunnel:secret:
    cmds:
    - |
        kubectl apply  -n argocd -f - << EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: cloudflared-secret
          namespace: networking
        stringData:
          TUNNEL_ID: "{{ .TUNNEL_ID }}"
          credentials.json: |
            {
              "AccountTag": "{{ .ACCOUNT_TAG }}",
              "TunnelSecret": "{{ .TUNNEL_SECRET }}",
              "TunnelID": "{{ .TUNNEL_ID }}"
            }
        EOF
    ignore_error: true

  tunnel:endpoint:
    cmds:
    - |
        kubectl apply -n argocd -f - << EOF
        ---
        apiVersion: externaldns.k8s.io/v1alpha1
        kind: DNSEndpoint
        metadata:
          name: cloudflared
        spec:
          endpoints:
            - dnsName: "external.chalk-ho.me"
              recordType: CNAME
              targets: ["{{ .TUNNEL_ID }}.cfargotunnel.com"]
        EOF

  # tunnel:config:
  #   cmds:


  default:
    cmds:
      - task: dns:secret
      - task: tunnel:secret
      - task: tunnel:endpoint
