apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server

namespace: kube-system

helmCharts:
- name: metrics-server
  repo: https://kubernetes-sigs.github.io/metrics-server
  version: 3.11.0
  namespace: kube-system
  valuesFile: values.yaml
  includeCRDs: true
