ignore: |
  templates/
  mkdocs.yml

extends: default

rules:
  document-start: disable
  line-length: disable
  indentation:
    spaces: consistent
    indent-sequences: whatever
  comments-indentation:
    level: warning
  braces:
    max-spaces-inside: 1
