ignore: |
  templates/
  mkdocs.yml

extends: default

rules:
  document-start: disable
  line-length: disable
  indentation:
    spaces: consistent
    indent-sequences: whatever
    check-multi-line-strings: false
  comments:
    level: warning
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
