apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-cloudflare
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  sources:
  - repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/networking/extenal-dns/cloudflare
    targetRevision: main
  destination:
    namespace: networking
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - ApplyOutOfSyncOnly=false
    - Prune=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 15m
