apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ./base

namespace: hass
patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/nodeSelector"
        value:
          kubernetes.io/hostname: metal-0
    target:
      kind: Deployment
      name: wyze-bridge

commonAnnotations:
  reloader.stakater.com/auto: "true"

images:
  - name: mrlt8/wyze-bridge
    newTag: 2.6.0-hw
