apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager-clusterissuer
spec:
  project: networking
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/networking/cert-manager-issuer
    targetRevision: main
  destination:
    namespace: cert-manager
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
