apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: networking
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/networking/external-dns
    targetRevision: main
  destination:
    namespace: networking
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ApplyOutOfSyncOnly=false
