apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-dns
  - ingress-nginx
  - tailscale-operator.yaml
  - cert-manager
  - certificates.yaml
  - kube-vip.yaml
# - unifi-controller.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: networking
