---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-dns.yaml
  - cert-manager.yaml
  - ingress-nginx/internal.yaml
  - ingress-nginx/external.yaml
  - k8s-gateway.yaml
# - nginx-ingress.yaml
# - tailscale-operator.yaml
# - tailscale.yaml
# - issuer.yaml
# - kube-vip.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: networking
