apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-dns
  - cert-manager.yaml
  - ingress-nginx.yaml
  - tailscale-operator.yaml
  # - tailscale.yaml
  - cert-manager-issuer.yaml
  - kube-vip.yaml
  # - unifi-controller.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: networking
