apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cilium.yaml
  - external-dns
  - ingress-nginx
  - tailscale-operator.yaml
  - cert-manager.yaml
  - certificates.yaml
  - k8s-gateway.yaml
  # - kube-vip.yaml
# - unifi-controller.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: networking
