---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: cert-manager  # XXX: Do not set this - it will override roles for kube-system needed for leader election of cainjector

resources:
  - ../base
