apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: squid-proxy-cloudflare
spec:
  secretName: proxy-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: proxy.chalk-ho.me
  dnsNames:
  - proxy.chalk-ho.me
