apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: squid-proxy
spec:
  ingressClassName: internal
  rules:
  - host: &host proxy.chalk-ho.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: squid
            port:
              name: proxy
  tls:
  - hosts:
    - *host
