# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-core-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  target:
    name: kube-prometheus-core-secrets
  data:
  - secretKey: GRAFANA_ADMIN_USER
    remoteRef:
      key: grafana
      property: username
  - secretKey: GRAFANA_ADMIN_PASSWORD
    remoteRef:
      key: grafana
      property: password
