apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "argo.chalk-ho.me"
    io.cilium/lb-ipam-ips: "10.10.0.2"
    tailscale.com/expose: "true"
    tailscale.com/hostname: "argocd"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.0.2
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
