apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.image-updater: apiKey
  kustomize.buildOptions: --enable-helm
  application.resourceTrackingMethod: annotation+label
  url: https://argo.chalk-ho.me
  statusbadge.enabled: "true"
  statusbadge.url: "https://argo.chalk-ho.me/"
  exec.enabled: "true"
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/reconcile/#system-level-configuration
  resource.ignoreResourceUpdatesEnabled: "true"
  resource.customizations.ignoreResourceUpdates.external-secrets.io_ExternalSecret: |
    jsonPointers:
    - /status/refreshTime
  # JQ equivalent of the above:
  # jqPathExpressions:
  # - .status.refreshTime
