---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets

resources:
  - cluster-secret-store.yaml

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    includeCRDs: false
    version: 0.9.11
    repo: https://charts.external-secrets.io
    valuesInline:
      fullnameOverride: external-secrets
      # resources:
      #   requests:
      #     cpu: 75m
      #     memory: 64Mi
      #   limits:
      #     cpu: 75m
      #     memory: 64Mi
      # podDisruptionBudget:
      #   enabled: true

      servicemonitor:
        enabled: true # true
        labels:
          prometheus.io/scrap-with: kube-prometheus-stack

namespace: external-secrets
