---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-secret-store
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: https://10.0.7.51
      vaults:
        Homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-credentials
            key: token
            namespace: onepassword
