replicaCount: 1

#image:
#  repository: ghcr.io/external-secrets/external-secrets
#  pullPolicy: IfNotPresent
#  # -- The image tag to use. The default is the chart appVersion.
#  # There are different image flavours available, like distroless and ubi.
#  # Please see GitHub release notes for image tags for these flavors.
#  # By default the distroless image is used.
#  tag: ""

installCRDs: false

crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: false
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- If true, external-secrets will perform leader election between instances to ensure no more
# than one instance of external-secrets operates at a time.
leaderElect: false

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Annotations to add to the service account.
  # XXX: TODO: put GKE Workload Identity / AWS IRSA integration annotations here
  annotations: {}
  # -- Extra Labels to add to the service account.
  extraLabels: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""
