version: '3'
vars:
  CYAN: tput setaf 6
  RED: tput setaf 1
  YELLOW: tput setaf 3
  GREEN: tput setaf 2
  BLUE: tput setaf 1
  PURPLE: tput setaf 5
  BG_B: tput setab 0
  BOLD: tput bold
  RESET: tput sgr0
  CLEAR: tput reset
  INT_REGISTRY: registry.localhost
  PATH_ERROR: is not installed or correctly configured in PATH.
  IMAGE_RENDERER_VERSION: 2.8.3

env:
  IMAGE_RENDERER_SOURCE_VERSION: 3.10.0

silent: true

tasks:

  build:
    cmds:
    - task: build:image-renderer
    - task: push:image-renderer

  
