apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:HOF295R0KNaBwsLUGIrbht/IYsjScr3DnoTpuDaCSh4j6VXA,iv:Ve8xL/zhznISCb92eoAt3ChW6+jQSMI/coErkki05hk=,tag:HHnkS5x5pAVrn+BSJEstdg==,type:str]
    credentials.json: ENC[AES256_GCM,data:H1yWHw94Tb85ewb7p9QdGwS+rTAwytOhGJEEW4srzSaWs1mxhoos9Mt+O7Ar9eFYzcipFKm2K+ThfqRM11TbDnMUAZnzUBfN2Puh45XoZsjGMTYNh7rEdBjP+xaE4OSPQUMlpOtZk58sIJiP7AdRtsN9w9FS0Tuy2R0K6GX3dkSIDCLEGIUaOgjJjdvWr0ub8dRlz7R9s9hEYPnRUJhsVpl7y8LK0m5gYDkYD9Jukg==,iv:Ji44yNqO4b2AZeBiMYXikgt8Y3oa/Ki3Fdq3FiC84wk=,tag:Ii7wkn+eu6s8QIKE8zlr+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUlBLdk91OWEvNy9OeVpR
            MTI3YndWRkZRWHlwMjc1L2h5ZHE4OTVJTGl3CnRsMGhTVlg0YVFRMmVVNmlPbndl
            TXI3NEhQU1lzYzJvTW8vcWhSTTQrS2sKLS0tIHRqWEZHLytudWc4NmdQNWM5emlE
            NXFJWDNQRWczaHlDV01jM3prV0NabTgK6jye2Z72gSjHkdz0d4iqx8Xcb47k8r2A
            bynTXI4F1+Hzk2KjRovHYv+KcZV814PuJ3n4Rl01JAS2x3rHFFAr7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T22:33:06Z"
    mac: ENC[AES256_GCM,data:KPhb7bAE71r+iVroVroi+ntiTaqUEuIjpkSsmh4f5j/KTU5kB3I+bOG0JrNhLvNCegwD90znAaQ1c2i1JJTeFBGKAM1gL2AzUdeUNRsgBPi4hbTzHhP/3+c/0VmRY7DHh3w8wvlzH959dbvrY9EtTM8mf+AZHqqrucGjDDdmOXA=,iv:IEVztWtJu12+8crx9xr0AMmn+IPm33nsrFTPXeMiKao=,tag:GI2vOzvttGU+hGfpTPT+Rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
