---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-certificates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/networking/ingress-nginx/certificates
    targetRevision: main
  destination:
    namespace: networking
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=false
