apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - nextdns.yamlapps/argocd/base/networking/external-dns/kustomization.yaml
  - external.yaml
  - internal.yaml
namespace: argocd

commonLabels:
  app.kubernetes.io/project: ingress-nginx
