apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:cAcNVxwUAwqm/OrXhTuFl8JSPtFx5w85,iv:O3IRLg5flBMrA8dWEoyTHN8cs1jfB2H1wQK+MMLh8wc=,tag:32yrHJ6/2KxRBtZB9t1sUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WWMxcGN1VWJtL0RHOXVs
            cFhONDZCeDI2cWhubHZTeS85V1VRdndhUlRRClBGdXcrU01IQ1ZJSnc5by9WSXNH
            cHFZbmczL0RKUVloVEdkWXlISlR6T00KLS0tIFl3bGN3c2JrQ20vclEvM09yTEVn
            S0QxN3Z4Z3M0R2E3Q3RXdzFBK2t6Ym8K7915bZtXi/uQBrxBY3LtiSN2vriPZP6Q
            HU4f0hPsVMIomgQDF5iDtqGN0HcFE/QFBX0XE1xTjDbn2nBmCSMkiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T04:02:19Z"
    mac: ENC[AES256_GCM,data:HDIRcJ6EOVRQiNrnBBwHOvJ1l8rT4sUJDvuahp0dZv7FYYzWAA194OjvRCOPc4bmuyNdF13Xmknb7xmdxlhy0cQuW/gWAtcxIENc09pkg81Vl/6WL9TiWH6AxUPneC0oQFp5pz2XF9+nGThfvGDZvWDzE7Bhuh1HnKauIsOE3mo=,iv:40m5fz77dTV8WVPXej1McpC3sI2fACOXoAbLuuRCg7U=,tag:jt1WKP33QcCvYRb8T4/FFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
