apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@chalk-ho.me
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector:
        dnsNames:
        - '*.chalk-ho.me'
        - chalk-ho.me
      dns01:
        cloudflare:
          email: admin@chalk-ho.me
          apiTokenSecretRef:
            name: cert-manager-secret
            key: CLOUDFLARE_API_TOKEN
