---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  labels:
    app.kubernetes.io/category: storage
spec:
  project: core
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/argocd/base/storage
    targetRevision: main
  destination:
    namespace: storage
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
