---
apiVersion: argoproj.io/v1alpha1
kind: Application
metastorage:
  name: storage
  namespace: argocd
  labels:
    app.kubernetes.io/category: storage
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/argocd/base/storage
    targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
