apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: onepassword

resources:
  - namespace.yaml

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts/
    version: 1.14.0
    releaseName: onepassword-connect
    namespace: onepassword
    includeCRDs: true
    valuesFile: values.yaml
