fullnameOverride: onepassword-connect

connect:
  # Denotes whether the 1Password Connect server will be deployed
  create: true

  # The number of replicas to run the 1Password Connect deployment
  replicas: 1

  # The name of 1Password Connect Application
  applicationName: onepassword-connect

  # The name of 1Password Connect Host
  host: onepassword-connect
  serviceType: LoadBalancer
  loadBalancerIP: 10.0.7.51
  httpPort: 80

  tls:
    enabled: true
    secretName: onepassword-connect-tls

  # ingressClassName: internal

  # hosts:
  #   - host: &host op-connect.chalk-ho.me
  #     paths: []
  # tls:
  #   - hosts:
  #       - *host
