---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openebs

helmCharts:
- name: openebs
  releaseName: openebs
  namespace: storage
  version: 3.10.0
  repo: https://openebs.github.io/charts
  valuesInline:
    localprovisioner:
      deviceClass:
        enabled: true
        name: openebs-device
        fsType: brfs
        isDefault: false
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        path: /var/openebs/local
        isDefault: false
