---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-ingress-nginx

helmCharts:
  - name: ingress-nginx
    releaseName: external
    namespace: networking
    includeCRDs: true
    version: 4.9.0
    repo: https://kubernetes.github.io/ingress-nginx
    valuesFile: values.yaml
    