apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:ZugJWybbuist+1pufCnov3Ya1T8=,iv:njHH65mEbMhOdY/R3kX511ELWy77iVks5FZfkfdNnEE=,tag:ZqpKsrJLSy9Dw5p8ea63Kw==,type:str]
    admin-user: ENC[AES256_GCM,data:ReaVyVg=,iv:MR9qVQCEspKcGaVj5qB9fLmzBUq2P6HCGY3NbY8nSTs=,tag:rYqaL8W2NXnMO+I3dIdO6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L092bGx0NkVWN29RRmhC
            bU96QXdCWkpSSnhDeHMxTmliWk9FdmowWGhzCkFIMUlUbHg3YzdwTHRMYy83eldh
            cXl2R2FhR21NbGhQTGg2c2hQRDhwS3cKLS0tIEszdmNpcC9Sb3NjenNldzZsZXpJ
            MlZ4ZjROZ0tRU2ttY3l3eE5mVTk4c3MKCOf3KpxJpye0pVKR0sbMKToVmNrUYSaw
            Cvr3W9U5AE+YFomCg/y2DizkU9EE72mOqqisjXzcrhFAd1f9fCZAnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T11:34:43Z"
    mac: ENC[AES256_GCM,data:cuMpTPcRFJ78Ktj0fxzUc272y/DLlX/4mxV3jdVr+C7R7d1xnpJOUkGzQDLXNSCrc/Icr+XwzJND3e50BfBhl6GNHRx4jRx5EwO4P6mEygs3q49NURJ04ZZWotyoYTh8iJH9lA3K9+aIfxE6L54wyj45Rp/MesE8VsUwnrOyRC0=,iv:awSosQn03hlig4rvyPWcXeUSuRGwGjVDCK9P/7idwXY=,tag:rLaQG5z/WhHGUeKHi52P+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
