---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  # renovate: datasource=helm depName=cilium repository=https://helm.cilium.io
  version: 1.15.0
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    autoDirectNodeRoutes: true
    bpf:
      masquerade: true
    cluster:
      name: homelab
      id: 1
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    endpointRoutes:
      enabled: true
    hubble:
      enabled: false
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: true
    ipv4NativeRoutingCIDR: "10.11.0.0/16"
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    localRedirectPolicy: true
    operator:
      replicas: 1
      rollOutPods: true
    hubble:
      tls:
        auto:
          enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      privileged: true
    bandwidthManager:
      enabled: true
      bbr: true
