apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy-a
  namespace: kube-system
spec: # CiliumBGPPeeringPolicySpec
  nodeSelector:
    matchLabels:
      bgp-policy: a
  virtualRouters: # []CiliumBGPVirtualRouter
    - localASN: 64500
      exportPodCIDR: true
      serviceSelector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ['never-used-value']}
      neighbors: # []CiliumBGPNeighbor
        - peerAddress: '10.0.7.1/32'
          peerASN: 64501
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
  namespace: kube-system
spec:
  cidrs:
    - cidr: "10.10.0.0/16"
  disabled: false
