---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
spec:
  project: storage
  source:
    repoURL: https://openebs.github.io/charts
    chart: openebs
    targetRevision: 3.10.0
    helm:
      releaseName: openebs
      valuesObject:
        localprovisioner:
          hostpathClass:
            enabled: true
            name: openebs-hostpath
            isDefaultClass: false
            basePath: "/var/openebs/local"
  destination:
    name: 'in-cluster'
    namespace: storage
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=false
