apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

patches:
  - patch: |-
      - op: add
        path: "/spec/loadBalancerClass"
        value: "--insecure"
    target:
      kind: Deployment
      name: argocd-server
