apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

#- external-secrets-aws-secret-store.yaml
#- external-secrets-gcp-secret-store.yaml
#- secret-store.yaml
#- external-secret.yaml

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts/
    version: 1.14.0
    releaseName: onepassword-connect
    namespace: external-secrets
    includeCRDs: true
    valuesFile: values.yaml
