apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:MqBTb16Ebow5ih/i90GOARvB1TEGXHkQEVMpya4Bw7aSSyLrcCJ2LQ==,iv:L08tsWXrZj5mjPuHdrSMCk5+iePHWrebHllZBa9M5NM=,tag:0pO/FfLLPAmdvb2uo3azZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZzdjUVB3R3ZwZkdMQjg0
            UHBlSE02aUd4VHdNb1FWSUVJZlF0bVdmbVhzCjJGK3kvcDhZaHhhKzlrSWhlbHlt
            N2VOWEZqWGh6eTlqRG9vNitid1JKNTgKLS0tIDkvb1NGajhzRUF5Q0dXUEdTbDFV
            QklndFJmRmdYVHl1Z1ZWQ3NpRlpPbDAKVLVXAOI/LT36a3UFjuwdoVLC/RftS4g8
            KY1XjyWExlLHnFazCy+fGyU5DTPwmgWiW7VKmW/Cu//cRHUY82Chaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T14:10:21Z"
    mac: ENC[AES256_GCM,data:ZM1WQAnCyqWiMJhmoVqeuZN2tgSctDox3aTMHU5bhscd9/T5CF9TaYlAeZprkx0JHBkRWQl8tclgLUhU6ZO3/8gLNXk+KYeFvuAR32H8U04vGMHjUagFyVCi1HvSav3/8uOP62wghSGT3Pb9+FghJRIWQp/LNIIhm9sVgaugEgY=,iv:Dm8E6nr+yu7zO6X4E+FiDVUc4DSqGYFbLfxsM5GFMf4=,tag:lV24QjfTvghexhqHLG74fA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
