apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:aXIcWGs9FQAFZr+nhYwv80cx+wLEbDQOVtSVdNNMavC8aKI6NFmTxQ==,iv:GpTxl4pGTmE6cOd/ELpOcpJuXjgmXe+ZmtzGhxJUPBo=,tag:DO6s3Qmbxbw3GYEUk+zxFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTGcxMDZTSU1XSHVzaTBJ
            aklTTjFSa0hSZUZqeCtwR1BBdUkveXpmS1U0CmFxSktCUHVNWmRZYXcwZ0tQc2ZR
            Z09tdk5OOHF6Tnl5TW5kWlpUc2FKNXMKLS0tIGxvem1SQW5zZE0rcDUvT3Z6YXNT
            UStPbElMcUNiWVA4UGhBa1FHaWZoRnMKjb1sjfFk0xz2MpGA8IVUU3vxnxn1sDIt
            Cn5EKC+vsAYo8GacuGSeLYNCbOdcxn0JCy21JGle0YkrJr5Nc0yyGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T23:14:42Z"
    mac: ENC[AES256_GCM,data:XoY6WwAlScCafTlIUt7e13sOWq2MrHsQr3gIGbrRbXTVWbicU55mVJj+Z+T9puxbd0eQBJhsQXAGpTVSm2W6ubD+hr1ybjdKAhNzdPKTJOnJLryI4MxRmWyn2cFn8IgE4l7rN+7gKQ5cm9zoXZLxWV7jlpDagYecQwBKT3grqKo=,iv:LqRI5piiN3OwwcryVUngRNa2lp6RBhhfM/s+40skav4=,tag:fM4N7yFQtAAaqwxQhxWjjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
