apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:XY6NWH8uHNKSMvzGgwXQ++KOS1+vsArP5xTktPuRirSLC/0M8fJs2A==,iv:tL3xsabLGcodc5HPZp6MaXyABp2e86Mq+D45Lf3nEmQ=,tag:6bTfiY7MYfhrgnIgQFbwNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQzE0dGhIVjl0VEN2NzhD
            YzZjd1cyZENEVm5zWVhhdDMySGphaXhLbXdFCnFEaUpNYjFqQUk3LzVzOFkzS0dq
            Qmd0N0xUTEpubDBya1JodzM3UWRvdEEKLS0tIEdNT0x1OHpMMUZ1ZDFDWnQ5ME00
            U2hpc0NwSzVTaklFdFNZcFNYSEdxQ28KWfGd2o+Zgy3h+LFldtVMu2P3XbRQrjJC
            AoHwR1sfvzYF1Q3OLqvuRpMwmbHiefAOIHFfHByFYsx46ahslnvJdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T00:59:34Z"
    mac: ENC[AES256_GCM,data:0I+QzM9TqqwIneX49+X2JB1zJvssFT9D7vNir94mnvbbfkBamIgKSCni1zznq7MJOkOYpNJMneGYEJK9tXX76w+jmPAQfvz5OzV6q+HaKw9w1qSRkSpA7NnZrrZfzDdcEXsUYCA4wdK5BJtusBMw5AR4ONhOcPHBpMu2bg/66A0=,iv:CvsoaQRD32yD+CR41TFOy2qoclGGSBPrubjP0Yz9Wh0=,tag:mStqMU14YDwNanE39yfNoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
