---
# yaml-language-server:$schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chalk-ho-me
spec:
  secretName: chalk-ho-me-cert
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  commonName: chalk-ho.me
  dnsNames:
    - chalk-ho.me
    - "*.chalk-ho.me"
