apiVersion: cert-manager.io/v1
kind: Secret
metadata:
  name: postgres-tls
  labels:
    cnpg.io/reload: ""
---
# yaml-language-server:$schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-tls
spec:
  secretName: postgres-tls
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
