---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: external.chalk-playground.space
      recordType: CNAME
      targets: ["28724a69-8809-4fe7-8615-0f1fe4fcd66b.cfargotunnel.com"]
    - dnsName: argo.chalk-playground.space
      recordType: CNAME
      targets: ["28724a69-8809-4fe7-8615-0f1fe4fcd66b.cfargotunnel.com"]

