---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: Locked down to only be used by ArgoCD
  orphanedResources:
    warn: false

  # sourceRepos:
  # - '*'

  destinations:
  - namespace: argocd  # should be the ArgoCD installation namespace
    # server: https://kubernetes.default.svc
    name: in-cluster

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
