---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
spec:
  description: Networking related Kubernetes resources
  sourceRepos:
    - '*'
  destinations:
    - namespace: storage
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
