apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base

namespace: hass

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: k8s-node-one
        kubernetes.io/arch: arm64
  target:
    kind: Deployment
    name: home-assistant

images:
- name: homeassistant/home-assistant
  newTag: "2024.1"

commonAnnotations:
  reloader.stakater.com/auto: 'true'
