---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-externalsecret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: operator-oauth
    template:
      engineVersion: v2
      data:
        client_id: "{{ .OAUTH_CLIENT_ID }}"
        client_secret: "{{ .OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tailscale
