apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # # ArgoCD Projects
  # - base/projects/core.yaml
  # - base/projects/cluster.yaml
  # - base/projects/monitoring.yaml
  # - base/projects/networking.yaml
  # - base/projects/apps.yaml
  # - base/projects/mlops.yaml
  # - base/projects/matrix.yaml

  # # Core apps
  # - base/core/argocd.yaml
  # - base/core/data.yaml
  # - base/core/nvidia.yaml
  # - base/core/nvidia-extra.yaml
  # - base/core/networking.yaml
  # - base/core/services.yaml
  # - base/core/utilities.yaml

  # # Applications
  # - base/apps/vault.yaml
  # - base/apps/ha.yaml
  # - base/apps/unifi.yaml
  # - base/apps/wyze.yaml

  # # Monitoring
  # - base/monitoring/kuma.yaml
  # - base/monitoring/unifi-poller.yaml
  # - base/monitoring/kube-prometheus.yaml
  # - base/monitoring/grafana.yaml
  # - base/monitoring/nvidia.yaml

  # ArgoCD
  - app/cmp-plugin.yaml
  - app/repo-role.yaml
  - app/repo-rb.yaml

  - https://github.com/chalk-hwang/home-ops/apps/networking/tailscale
  - https://github.com/chalk-hwang/home-ops/apps/networking/cloudflared
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml
  - app/styles-cm.yaml

namespace: argocd
images:
  - name: quay.io/argoproj/argocd
    newTag: v2.9.3
patches:
  - patch: |-
      - op: replace
        path: "/metadata/namespace"
        value: "monitoring"
    target:
      kind: ServiceMonitor
  - patch: |-
      - op: add
        path: "/spec/strategy"
        value:
          type: "Recreate"
      - op: replace
        path: "/spec/template/spec/serviceAccountName"
        value: "argocd-server"
    target:
      kind: Deployment
      name: argocd-server
  - patch: |-
      - op: add
        path: "/spec/template/spec/nodeSelector"
        value:
          kubernetes.io/hostname: k8s-node-one
          kubernetes.io/arch: arm64
    target:
      kind: Deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/nodeSelector"
        value:
          kubernetes.io/hostname: k8s-node-one
          kubernetes.io/arch: arm64
    target:
      kind: StatefulSet
  - patch: |-
      - op: replace
        path: "/spec/template/spec/volumes/0/secret/secretName"
        value: "argo-tunnel"
    target:
      kind: Deployment
      name: cloudflared
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/args/-"
        value: "--insecure"
    target:
      kind: Deployment
      name: argocd-server
  - path: overlay/argocd-svc.yaml
  - path: overlay/argocd-server.yaml
  - path: overlay/argocd-repo-server.yaml
  - path: overlay/argocd-cm.yaml
  - path: overlay/cloudflared-cm.yaml
  - path: overlay/argocd-rbac.yaml
  - path: overlay/argocd-cr.yaml
commonAnnotations:
  reloader.stakater.com/auto: "true"
