---
- name: Cluster Installation
  hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Check if cluster is installed
      check_mode: false
      ansible.builtin.stat:
        path: /etc/rancher/k3s/config.yaml
      register: k3s_installed

    # - name: Ignore manifests templates and urls if the cluster is already installed
    #   when: k3s_installed.stat.exists
    #   ansible.builtin.set_fact:
    #     k3s_server_manifests_templates: []
    #     k3s_server_manifests_urls: []

    - name: Prevent downgrades
      when: k3s_installed.stat.exists
      ansible.builtin.include_tasks: tasks/version-check.yaml

    - name: Install Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: installed

    - name: Kubeconfig
      ansible.builtin.include_tasks: tasks/kubeconfig.yaml

    - name: Cilium
      when: k3s_primary_control_node
      block:
        - name: Cilium | already installed
          ansible.builtin.command: cilium version
          register: cilium_installed
          changed_when: false
          failed_when: false
        - name: Cilium | Install CLI
          vars:
            CILIUM_CLI_VERSION:
              sh: curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
            CILILUN_CLI_PKG_URL: https://github.com/cilium/cilium-cli/releases/download/{{ CILIUM_CLI_VERSION }}/cilium-linux-{{ ansible_architecture }}.tar.gz
          when: cilium_installed.rc != 0
          become: true
          ansible.builtin.get_url:
            url: "{{ CILILUN_CLI_PKG_URL }}"
            dest: "/usr/local/bin/cilium"
            checksum: "sha256={{ CILILUN_CLI_PKG_URL }}.sha256sum"
            decompress: true
            mode: 0755
          # ansible.builtin.shell:
          #   cmd: |-
          #     CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
          #     CLI_ARCH=arm64
          #     [ "$(uname -m)" = "aarch64" ] && CLI_ARCH=arm64
          #     curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
          #     sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
          #     tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
          #     rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
          #   creates: /usr/local/bin/cilium


    # - name: Wait for custom manifests to rollout
    #   when:
    #   - k3s_primary_control_node
    #   - (k3s_server_manifests_templates | length > 0 or k3s_server_manifests_urls | length > 0)
    #   kubernetes.core.k8s_info:
    #     kubeconfig: /etc/rancher/k3s/k3s.yaml
    #     kind: "{{ item.kind }}"
    #     name: "{{ item.name }}"
    #     namespace: "{{ item.namespace | default('') }}"
    #     wait: true
    #     wait_sleep: 10
    #     wait_timeout: 360
    #   loop:
    #   - { name: cilium, kind: HelmChart, namespace: kube-system }

    # - name: Cilium
      # when: k3s_primary_control_node
      # ansible.builtin.include_tasks: tasks/cilium.yaml

    - name: Cruft
      when: k3s_primary_control_node
      ansible.builtin.include_tasks: tasks/cruft.yaml
