---
- name: Prepare System
  hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
    - name: Populate service facts
      ansible.builtin.setup:
  tasks:
    - name: Locale
      block:
        - name: Locale | Set timezone
          community.general.timezone:
            name: "Asia/Seoul"

    - name: Packages
      block:
        - name: Packages | Install
          ansible.builtin.dnf:
            name:
              - apt-transport-https
              - ca-certificates
              - conntrack
              - curl
              - dirmngr
              - gdisk
              - gnupg
              - hdparm
              - htop
              - iptables
              - iputils
              - ipvsadm
              - libseccomp
              - lm_sensors
              - neofetch
              - net-tools
              - nfs-utils
              - nvme-cli
              - iscsi-initiator-utils
              - parted
              - psmisc
              - python3
              - python3-libs
              - python3-kubernetes
              - python3-yaml
              - smartmontools
              - socat
              - unzip
              - util-linux

    - name: User Configuration
      block:
        - name: User Configuration | SSH keys
          ansible.posix.authorized_key:
            user: "{{ ansible_user }}"
            key: "https://github.com/chalk-hwang.keys"
        - name: User Configuration | Silence login
          ansible.builtin.file:
            dest: "{{ '/home/' + ansible_user if ansible_user != 'root' else '/root' }}/.hushlogin"
            state: touch
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: "0644"
            modification_time: preserve
            access_time: preserve

    - name: Fish
      block:
        - name: Fish | Install fish
          ansible.builtin.dnf:
            name: fish
        - name: Fish | Set as default shell
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            shell: /usr/bin/fish
        - name: Fish | Create configuration directory
          ansible.builtin.file:
            path: "{{ '/home/' + ansible_user if ansible_user != 'root' else '/root' }}/.config/fish/functions"
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            recurse: true
        - name: Fish | Create neofetch greeting
          ansible.builtin.copy:
            dest: "{{ '/home/' + ansible_user if ansible_user != 'root' else '/root' }}/.config/fish/functions/fish_greeting.fish"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: "0755"
            content: neofetch --config none
        - name: Fish | Create kubectl shorthand
          ansible.builtin.copy:
            dest: "{{ '/home/' + ansible_user if ansible_user != 'root' else '/root' }}/.config/fish/functions/k.fish"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: "0755"
            content: |
              function k --wraps=kubectl --description 'kubectl shorthand'
                  kubectl $argv
              end

    - name: Network Configuration
      notify: Reboot
      block:
        - name: Network Configuration | Set hostname
          ansible.builtin.hostname:
            name: "{{ inventory_hostname }}"
        - name: Network Configuration | Update hosts
          ansible.builtin.copy:
            content: |
              127.0.0.1 localhost
              127.0.1.1 {{ inventory_hostname }}

              # The following lines are desirable for IPv6 capable hosts
              ::1     localhost ip6-localhost ip6-loopback
              ff02::1 ip6-allnodes
              ff02::2 ip6-allrouters
            dest: /etc/hosts
            mode: preserve
        # https://github.com/onedr0p/flux-cluster-template/discussions/635
        - name: Network Configuration | Remove immutable flag from /etc/resolv.conf
          ansible.builtin.file:
            attributes: -i
            path: /etc/resolv.conf
        - name: Network Configuration | Remove /etc/resolv.conf
          ansible.builtin.file:
            attributes: -i
            path: /etc/resolv.conf
            state: absent
        - name: Network Configuration | Add custom /etc/resolv.conf
          ansible.builtin.copy:
            attributes: +i
            mode: '0644'
            dest: /etc/resolv.conf
            content: |
              search .
              nameserver 10.0.5.254

    - name: System Configuration
      notify: Reboot
      block:
        - name: System Configuration | Neofetch
          ansible.builtin.copy:
            dest: /etc/profile.d/neofetch.sh
            mode: "0755"
            content: "neofetch --config none"
          notify:
            - Reboot
        # - name: System Configuration | Disable SELinux
        #   ansible.builtin.lineinfile:
        #     dest: /etc/selinux/config
        #     regexp: "^SELINUX="
        #     line: "SELINUX=disabled"
        #     state: present
        #   notify:
        #     - Reboot
        - name: System Configuration | Disable swap
          ansible.posix.mount:
            name: "{% raw %}{{ item }}{% endraw %}"
            fstype: swap
            state: absent
          loop:
            - none
            - swap
        - name: System Configuration | Create Kernel modules
          ansible.builtin.copy:
            dest: "/etc/modules-load.d/{{ item }}.conf"
            mode: "0644"
            content: "{{ item }}"
          loop:
            - br_netfilter
            - ceph
            - ip_vs
            - ip_vs_rr
            - nbd
            - overlay
            - rbd
          register: modules_status
        - name: System Configuration | Reload Kernel modules  # noqa: no-changed-when no-handler
          when: modules_status.changed
          ansible.builtin.systemd:
            name: systemd-modules-load
            state: restarted
        - name: System Configuration | Sysctl
          ansible.posix.sysctl:
            name: "{{ item.key }}"
            value: "{{ item.value }}"
            sysctl_file: /etc/sysctl.d/99-kubernetes.conf
            reload: true
          loop:
            - { key: "fs.inotify.max_queued_events", value: "65536" }
            - { key: "fs.inotify.max_user_watches", value: "524288" }
            - { key: "fs.inotify.max_user_instances", value: "8192" }

    - name: Tailscale
      block:
        - name: Tailscale | Install
          ansible.builtin.include_role:
            name:  artis3n.tailscale
            public: true
          vars:
            verbose: true
            tailscale_authkey: "{{ lookup('env', 'TAILSCALE_METAL_OAUTH_CLIENT_SECRET') }}"
            tailscale_tags:
              - "metal"
            tailscale_args: "--ssh --advertise-connector --accept-dns=true --advertise-routes=10.0.7.0/24,10.42.0.0/16,10.43.0.0/16 --accept-routes=true"
            # Optionally, also include:
            tailscale_oauth_ephemeral: false
            tailscale_oauth_preauthorized: true

  handlers:
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
