apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-cloudflare

resources:
- externalsecret.yaml

#- external-secrets-aws-secret-store.yaml
#- external-secrets-gcp-secret-store.yaml
#- secret-store.yaml
#- external-secret.yaml

helmCharts:
- name: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns
  version: 1.14.3
  namespace: networking
  valuesFile: values.yaml
  includeCRDs: false
