apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base

namespace: hass

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/nodeSelector"
        value:
          kubernetes.io/arch: arm64
    target:
      kind: Deployment
      name: whisper
