apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Vn8jHo4=,iv:zOIxzreSuxOL2lZRM4FEpaN4hsXTlJFAz+qHZnfUhrA=,tag:8uTdI1jrqQ150MsEKy0pIA==,type:str]
    password: ENC[AES256_GCM,data:U52e4ESSxWJdkB0pw2Rk6E8epbz9GA8vraicne26hSFcZ3wPXSZnTyHLXtTaU6I0v1g0aQ9X64w/lk5F,iv:DGVbNq6Io4tWciHtUmMeaVryu1YdlFSfh0qq+xtydEY=,tag:PJ78V5zLmir3fNbYO8oLEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRnpaZ0o5Q1Q3VTFNSTM3
            c05Tc1ZRMTk2K0lHRDVsSVh3SkJNTXl1K1hzCi9Jd1pkNmREbHlzeDduYWFqN05E
            R3N4UW5ZMjdtNitKV1FOTXR6eFRMejAKLS0tIFZoenpjK1M4Y2pBSFd5TGVYQ2pn
            Z0dnQWVDMlJrNXFrNDU5VnE3WnZTaHMK/yKpI1+5Wa7FwTohROjYjDiAXL1jxInV
            A0u19GHo+MhB/K0XC4lwIc2Iw5EDuO9iYV/VEMLPft0FKWEpwqVSdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T00:59:34Z"
    mac: ENC[AES256_GCM,data:j0aW8a8YhiMlFy41+S5yllb2Dm4d2l0lwiVrPQCeiu+rTHeoGn9Il425j9rEkFH6D9OcixRRQfkC9ZhFPgT4BzSOhmSch1+BcLLr7q4hxiCcVokvJTzcWhKqT1sCjzMZBHo83DS7ztdfVrwbf9aZtwSwsvPWiCVGIKwfsP/MgJo=,iv:WXfkA/BV9XDSYvmpoamouv2T+yrEkVum3fsUsJacxm4=,tag:hp6GTROG8cV/arI4DWgPVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
