---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - base/crds
- base/projects.yaml

# Core apps
- base/core/argocd.yaml
- base/core/networking.yaml
- base/core/storage.yaml
- base/core/utilities.yaml

# ArgoCD
- base/repo-role.yaml
- base/repo-rb.yaml

# - https://github.com/chalk-hwang/home-ops/apps/networking/tailscale
- https://github.com/chalk-hwang/home-ops/apps/networking/cloudflared

# - base/cloudflared-dnsendpoint.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml
- base/styles-cm.yaml

namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newTag: v2.9.3
patches:
  - patch: |-
      - op: replace
        path: "/metadata/namespace"
        value: "monitoring"
    target:
      kind: ServiceMonitor
  - patch: |-
      - op: add
        path: "/spec/strategy"
        value:
          type: "Recreate"
      - op: replace
        path: "/spec/template/spec/serviceAccountName"
        value: "argocd-server"
    target:
      kind: Deployment
      name: argocd-server
  - patch: |-
      - op: add
        path: "/spec/template/spec/nodeSelector"
        value:
          kubernetes.io/hostname: metal-0
          kubernetes.io/arch: arm64
    target:
      kind: Deployment
  - patch: |-
      - op: add
        path: "/spec/template/spec/nodeSelector"
        value:
          kubernetes.io/hostname: metal-0
          kubernetes.io/arch: arm64
    target:
      kind: StatefulSet
  - patch: |-
      - op: replace
        path: "/spec/template/spec/volumes/0/secret/secretName"
        value: "home-tunnel"
    target:
      kind: Deployment
      name: cloudflared
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/args/-"
        value: "--insecure"
    target:
      kind: Deployment
      name: argocd-server
  - path: overlay/argocd-svc.yaml
  - path: overlay/argocd-deployment.yaml
  - path: overlay/argocd-cm.yaml
  - path: overlay/cloudflared-cm.yaml
  - path: overlay/argocd-rbac.yaml
  - path: overlay/argocd-cr.yaml
commonAnnotations:
  reloader.stakater.com/auto: "true"
