apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant.yaml
  # - openwakeword.yaml
  # - piper.yaml
  # - whisper.yaml
  # - wyze.yaml
  # - external-mic.yaml
  # - satellite.yaml

namespace: argocd
