---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- external-secrets.yaml
- onepassword-connect.yaml

namespace: utilities

commonLabels:
  app.kubernetes.io/category: utilities
