---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- onepassword-connect.yaml
- external-secrets.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: utilities
