apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- reflector.yaml
- reloader.yaml
- onepassword-connect.yaml
- external-secrets.yaml
- descheduler.yaml
- kured.yaml
- botkube.yaml
- trivy-operator.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: utilities
