apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
spec:
  project: cluster
  source:
    repoURL: "https://github.com/chalk-hwang/home-ops.git"
    path: apps/utilities/onepassword-connect
    targetRevision: main
  destination:
    namespace: external-secrets
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - Validate=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
