---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true


    automated:
      prune: false
      selfHeal: true

  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts/
    targetRevision: 1.14.0

    # https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
    helm:
      valuesObject:
        fullnameOverride: onepassword-connect
        connect:
          serviceMonitor:
            enabled: true # true
          tls:
            enabled: true

        # Use workload identity to give the external-secrets pod access to the GCP Secret Manager API.
        # serviceAccount:
        #   annotations:
        #     iam.gke.io/gcp-service-account: external-secrets@${ARGOCD_ENV_PROJECT}.iam.gserviceaccount.com

  destination:
    name: in-cluster
    namespace: external-secrets
