apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://aquasecurity.github.io/helm-charts/
    chart: trivy-operator
    targetRevision: 0.20.6
    helm:
      releaseName: trivy-operator
      values: |
        trivy:
          command: filesystem
          ignoreUnfixed: true
        trivyOperator:
          scanJobPodTemplateContainerSecurityContext:
            # For filesystem scanning, Trivy needs to run as the root user
            runAsUser: 0
  destination:
    namespace: trivy-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=background
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
