apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:mfKbn7TZukV/Z3R9,iv:VoQHXKnaMldd7nlUkCN/+s5X3Ngsqo7q3CU9CWh5eTM=,tag:fqBfe3c7lzz9O6hbnB/TbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWXhKRll3THBlNm5TTUta
            TFNEVWFidGZiRW5XMnRiMEdiMjhaNkZvQzJvCk5mRUtZQ2FMVUlmM2N3d0E3YVgv
            T2YyYk16ZWYzb2dKZ1ZSVmxUVXF2WEUKLS0tIGRENklGdGJqWkNTa0xwbWtsKzgx
            MjlhZ0pSWTVDZ1NVdzBJZklBSTd0N00Ky5P+pQ7kmc3LQgYcXSVNCD8Fh+YKbO/o
            TT/R/XBQYAz9zNMGIPPRHIAJNlpcg8rbJphbxTxgfqI9Ie4G98N9Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-12T11:19:53Z"
    mac: ENC[AES256_GCM,data:8CWscMiNSL2/ENWmD8Id4HyfeOgruDLU28hA+rjll/JukX1O5/nOwzwdRHmZ3fd1VULV7QVJDJt1b4sxEOfTutbn95sAx9bfBVM70vuOQvo3pxBB/0BuSaIUKBhvIpkDNYxHYZCnKA7+arECJHloM9NB6ezCMRdCfO5hna3nzgA=,iv:qypzOVomJzOt0gvduaZj0t6+e36cu1rNyehADIYCjbE=,tag:0MIRky3mU8ndRDtRjZc75A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
