apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:t9fjviNbDHUAlRmT,iv:K9kRT0qSUKIyYHg8KP27GQC1+br+dlBatNiSLrb51yA=,tag:U+8cHK9S2jQWFgeuI9iu6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV1h0ekFDd2F3Y3c0bWxw
            VjlRalhBeDdQcXZxblNJQWk4dEthTFJtL1RZClk0d2VCdzR1UEE5NFJUVW1YTG1r
            Uk1ua2J0dGpDN0I0SGRNVlUvTy83eHMKLS0tIGw5TXdhamFLMW52VDZTL1dPZ0VO
            V0d6M2FKbUkrYSsyamdoYXljRS9TQU0KiYZ0ik8kj+IELoZl7Tni8eOeqks2j+uI
            CnBAtSQfmID3eGpctLlBQzG96kBbyAbThhMsmdpHs4fy0349CEKXRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T22:37:54Z"
    mac: ENC[AES256_GCM,data:NnJuw4eF2YRaaVGcy0UsPvVbGiFrTY4gbz49FvYDzKA8NiBZEWLdhPCm10nuaYalbjqcSUHMZiTVEt688PXWp/nB02z1T+q8+GjuNV7T9bhy2NK+HZuqW0bLjbsU9zjd7MNJrNUnxs/FjvKIwB3Bs5r0Qe5g+3CHWtOqMZK6uCU=,iv:pRdY0N/VMWrJP3qDQBnVYFx11scqgzhPzqX1yToSMnk=,tag:lCLNMvX9RiGV3YCGHV2Zbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
