apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:wwj8Teth/pwxXeHQAB3hTjmonKpfeSRqypkwlQ==,iv:l3m3oPO/rN0uk/LnxprBPwP3YfYtLuOfYxEFW54Lv3E=,tag:Xyo7uZBW6lmhM5/TCRMV7A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Wg8QlLe9VAqduLDprhh7vf6FKMHYYjPIcLCLYbE976CXZCet,iv:TC0MqEDdadn6t6OszCGT1sa6kuRVeFIrRpBWEG84CPc=,tag:bEmn6t3v0EoPVQ1qflhaFQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Zf7y4cQIAtVXlMdQtyFyw/GPrwWA9w==,iv:MokGtkIpNKhaaDnW9pC2gbXW7n5RSrs6Du5xiFyAq+w=,tag:kkoffFmSx2A6CijPhk1w8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTDhYVnhoQnpBdXA4bTRG
            UEJHQ3FhK3o4bHYweW8xS3JjWElNVjVVY1IwCnB2Q0lyb3l1QXBYUUpoTHpmclB2
            R09rVmdaZWhkRnFTaE9yS1JJd2ZKZU0KLS0tIGl4M0c3SjZoQ3JrQ0pGYi9qZDBG
            eENXOHJybWlTV3M0UG9WSndrMkRGbDAKQ8nH8yImnYXLAMH80pqfSEy6AerEQY2d
            /2tWY21o0n97c2sxMJYwpbmRZSWwbDg7BAuDbiGu0HKhYP3qnEJDqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T07:12:41Z"
    mac: ENC[AES256_GCM,data:irT5aTVwx3br2sv0FFkD4ZrdtilBehfyhTichLqBzfmWLJfT9d5kud5z16wC52LWdrue3TNo0zm98zsuKeQFkgI2HCoO/YdMaaaN3spBsY5wlGZ83n6AORooQz8h5xWj2Qf1245naYLBuBzxJMt45aNp4AoP8dz/etR/7WLPKks=,iv:UM/PQGtVf3W70N9CBJBYt74KZ/5TuYMKIRw/QtINqFc=,tag:LQRVvtlQOphxNsi8VfzYsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
