apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:HJW/+s8Rv+dQtiMi,iv:+uNhRfjOlnCdeTm41KIL2FTADx567v5fCsEmOxd99w4=,tag:yREt7maVZ4+wjAtSVTwR1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVXgwbURsZDJUWUZrZlZm
            MDBYM1lUZnZsblpsaDlvOGF6bzNTOUhCMkNVCk5HY2RWdDNRQkhrcmhTZ2dxa2Y0
            bkt0OTRQQXBhVThVZUpqcmE4UHV6ZFUKLS0tIFpJNVJncnlQOENCMHdZdHZjeEhr
            SnV3UDFoak0xaTJjcTVwY0o1UmpUSjQKWpssyvBu4+Tv1mSJIq856Fdq+q6xR4h2
            0ht1HqTF6dzVFToP0is8wYzUqq1g6mYLTYCW++KTAksvZp49ewUfeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T07:33:00Z"
    mac: ENC[AES256_GCM,data:Fj0RM9U/LavHVCEdgtGGJoyiXBgEpSUJ/p/hG65cKmwQTmxxPsyLql0budMamzNQx9zSB1fN31mzF0e6LcJkxUuEPcFF0NgN0NQ2NdphRu2NmMXVF0oZ4M4U2fePZKmQGwXgVDHIIAtpV6yZXotyrIK1JeowDAGx+Gnuo+cvYHc=,iv:ausgboed4EmhAMrowSa6n2WCfOTW3OCR/m7f95PhU8w=,tag:qkE48o5RuYV4E65a2fqECg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
