apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:bmAAk9Vg2qMAqQMH,iv:oJe4+gNJhKVgUWbu9Agv9iqMS3xBlwGB0MPX8xqPp+8=,tag:RkZ3vKnRsZ73nfusBmBNFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd1lXSmlKT0FaWHlzWCsx
            TDhKaytWUGdJTkZhQ2RWWjh5MUlReDhUbUU4Ck5lOTNBM0p0VThvbGpZRmduR3d3
            ZTV6UjZSRDQ0NlE4Z25LN3lEWjhKZFUKLS0tIFVrMk96NWc1REgrSUYycDFta1Vz
            bTY3ZUtnVjY0YVBhL1N0a1F4cVNNOGcKmusR2kwKvDdqSnNY0qU3unZN0B1Ptzje
            0gl7R+H4kqmix6NvsbBm2mp4VjQSPy60L9nZV68W2nHFtyIfHIgw6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T07:12:41Z"
    mac: ENC[AES256_GCM,data:9KeaN1neFJCA942N3mK3p0dIzPKNWeH7JohdrJbhaHXwVfhXBxafPQF3EvKlrmNr2UBGg3tmg3TeblXaXpwwiQLXeyctYnEGDryQW9Nn+2wCFXn0uF+RVkgJqOjGH6+OWbq7OGO+TcEn42CysBhUSvcxd3QBSFQY4oZK9yw3rrQ=,iv:jSHD2UEGsoj9h5x/MiDR9kMnOTeWPHjFJ9AJ6VC8gBo=,tag:x0+lolXkuUUdZgThDIhtcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
