---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    app: argocd
  annotations:
    pref.argocd.argoproj.io/default-view: network
spec:
  project: core
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: argocd
    targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        prometheus: enabled
    syncOptions:
    - ApplyOutOfSyncOnly=false
    - CreateNamespace=true
