apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  labels:
    app.kubernetes.io/category: home-assistant
spec:
  project: apps
  source:
    repoURL: "https://github.com/chalk-hwang/home-ops.git"
    path: argocd/base/home-assistant
    targetRevision: main
  destination:
    namespace: hass
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    managedNamespaceMetadata:
      labels:
        prometheus: enabled
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
