---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking
  namespace: argocd
  labels:
    app.kubernetes.io/category: networking
spec:
  project: default
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: argocd/base/networking
    targetRevision: main
  destination:
    namespace: networking
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=false
    - CreateNamespace=true
