apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-gateway
spec:
  project: networking
  source:
    repoURL: https://ori-edge.github.io/k8s_gateway
    chart: k8s-gateway
    targetRevision: 2.3.0
    helm:
      releaseName: local-gateway
      values: |
        fullnameOverride: local-gateway
        domain: "chalk-ho.me"
        ttl: 1
        secondary: tailscale-gateway.networking
        service:
          type: LoadBalancer
          port: 53
          loadBalancerIP: 10.10.0.254
          annotations:
            io.cilium/lb-ipam-ips: "10.10.0.254"
          externalTrafficPolicy: Cluster
  destination:
    namespace: networking
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 60m
