apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ingress-cert
spec:
  secretName: grafana-tls
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  commonName: grafana.chalk-ho.me
  dnsNames:
  - grafana.chalk-ho.me
