apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium

namespace: kube-system

resources:
  - bgp-peering-policy.yaml
  - lb-ip-pool.yaml

helmCharts:
  - name: cilium
    version: 1.15.1
    repo: https://helm.cilium.io/
    namespace: kube-system
    releaseName: cilium
    valuesFile: values.yaml
    includeCRDs: true
