apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - nextdns.yaml
  - internal.yaml
  - external.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/project: ingress-nginx
