apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/chalk-hwang/home-ops.git'
    path: apps/monitoring/kube-prometheus
    targetRevision: main
  destination:
    namespace: monitoring
    name: in-cluster
  info:
  - name: "Github Repository:"
    value: >-
      https://github.com/prometheus-operator/kube-prometheus
  - name: "Chart location:"
    value: >-
      https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
  - name: "Official Website:"
    value: >-
      https://prometheus-operator.dev/
  - name: "Documentation:"
    value: >-
      https://prometheus-operator.dev/docs/prologue/introduction/
  - name: "k3s useful documentation:"
    value: >-
      https://picluster.ricsanfre.com/docs/prometheus/#k3s-components-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 20m
  # See: https://github.com/prometheus-community/helm-charts/issues/1041
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: kube-prometheus-kube-prome-admission
    jsonPointers:
    - /webhooks/0/failurePolicy
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: kube-prometheus-kube-prome-admission
    jsonPointers:
    - /webhooks/0/failurePolicy
