apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
spec:
  project: apps
  source:
    repoURL: "https://github.com/chalk-hwang/home-ops.git"
    path: apps/home-assistant/core
    targetRevision: main
  destination:
    namespace: home-assistant
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=false
      - Prune=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
