apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-mic
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: "https://github.com/chalk-hwang/home-ops.git"
    path: apps/home-assistant/external-mic
    targetRevision: main
    kustomize:
      commonLabels:
        app.kubernetes.io/category: home
  destination:
    namespace: home-assistant
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Prune=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
  info:
    - name: "Github Repository:"
      value: >-
        https://github.com/rhasspy/wyoming-mic-external
    - name: "Homelab documentation:"
      value: >-
        https://github.com/chalk-hwang/home-ops/tree/main/apps/home/external-mic
