---
extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: false
  line-length: false
  braces:
    forbid: false
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1

