---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../../base/networking/ingress-nginx

patches:
  - target:
      group: kustomize.config.k8s.io
      version: v1beta1
      kind: Kustomization
      name: ingress-nginx-internal
      namespace: networking
    patch: |-
      - op: replace
        path: "/helmCharts/0/releaseName"
        value: ingress-nginx-external
      - op: replace
        path: "helmCharts/0/valuesInline/fullnameOverride"
        value: ingress-nginx-external
      - op: replace
        path: "helmCharts/0/valuesInline/controller/annotations/external-dns.alpha.kubernetes.io~1hostname"
        value: external.chalk-playground.space
      - op: replace
        path: "helmCharts/0/valuesInline/controller/annotations/cilium.io~1lb-ipam-ips"
        value: "10.0.7.4"
      - op: replace
        path: "helmCharts/0/valuesInline/controller/ingressCalassResource/name"
        value: external
      - op: replace
        path: "helmCharts/0/valuesInline/controller/ingressCalassResource/default"
        value: false
      - op: replace
        path: "helmCharts/0/valuesInline/controller/ingressCalassResource/controllerValue"
        value: k8s.io/external
      - op: replace
        path: "helmCharts/0/valuesInline/controller/admissionWebhooks/objectSelector/matchExpressions/0/values/0"
        value: external
      - op: replace
        path: "helmCharts/0/valuesInline/controller/topologySpreadConstraints/0/labelSelector/matchLabels/app.kubernetes.io~1instance"
        value: ingress-nginx-external

