version: "3"

silent: true

tasks:
  secret:
    cmds:
      - |
        kubectl apply -f - << EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: op-credentials
          namespace: onepassword
        type: Opaque
        stringData:
          1password-credentials.json: $(op read "op://Private-Homelab/Production_CredentialsFile/1password-credentials.json" | base64)
        EOF
      - |


  connect:
    dir: apps/utilities/onepassword-connect
    preconditions:
      - sh: "which kustomize"
        msg: "kustomize {{.PATH_ERROR}}"
      - sh: "which kubectl"
        msg: "kubectl {{.PATH_ERROR}}"
    cmds:
      - kubectl create namespace onepassword
      - kustomize build --enable-helm | kubectl apply -f -
      - task: secret
      - echo "Patched secret."
    ignore_error: true

  default:
    cmds:
      - task: connect

