apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: argo-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: argo.chalk-ho.me
      service: http://argocd-server:80
    - hostname: chalk-ho.me
      service: https://nginx-external-controller.network.svc.cluster.at.chalk.ho.me:443
      originRequest:
        http2Origin: true
        originServerName: external.chalk-ho.me
    - hostname: "*.chalk-ho.me"
      service: https://nginx-external-controller.network.svc.cluster.at.chalk.ho.me:443
      originRequest:
        http2Origin: true
        originServerName: external.chalk-ho.me
    - service: http_status:404
