apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: argo-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: argo.chalk-playground.space
      service: http://argocd-server:80
    - hostname: chalk-playground.space
      service: https://nginx-external-controller.network.svc.cluster.local:443
      originRequest:
        http2Origin: true
        originServerName: external.chalk-playground.space
    - hostname: "*.chalk-playground.space"
      service: https://nginx-external-controller.network.svc.cluster.local:443
      originRequest:
        http2Origin: true
        originServerName: external.chalk-playground.space
    - service: http_status:404
