---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: operator
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # oauth:
    #   clientId: "{{ .Values.clientId }}"
    #   clientSecret: "{{ .Values.clientSecret }}"
    podAnnotations:
      secret.reloader.stakater.com/reload: operator-oauth
