---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - stores/onepassword-connect.yaml

  #- external-secrets-aws-secret-store.yaml
  #- external-secrets-gcp-secret-store.yaml
  #- secret-store.yaml
  #- external-secret.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.11
    releaseName: external-secrets
    namespace: external-secrets
    includeCRDs: true
    valuesFile: values.yaml
