apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:+H6nnhSZfh622gJLehK+9DHQOkwXPT0rsur5IPblUgcaCyeMHDnzWw==,iv:24Swl3TcO1R5yknyFs7IAYpVKkrlrqGccRIGedu35zQ=,tag:RQgk83gZWuzbj5rqFCX8MQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRTRwblBldTVlcFdTUkJX
            cVFScWdIK0N2WmJ3VW5SSXhmSXUzMDJqdHhnCk9NVFZPb0Zpd2ozR1ovNEVSTHRk
            N1V1L1ZVNkUxdnNUK1dlYWZjSDhmSU0KLS0tIFc1azRkeFhONWFtdXplUlU2eWcw
            R2wyYm9mMEN6dE9DUlgydzExOHZRZHMKqqQIOgNZc61lsP8D2Zt1btipbQAaN05r
            exBUdQvJp/JCQybsAOMIYpSErsFpYwDb0yWfS5Lg7qc3fzDtUXvzZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T22:33:06Z"
    mac: ENC[AES256_GCM,data:eNI1a7A6sxKSEcvxjYc762ooEI9zN7LBNJb7bflvIhw7vWp7/v7q0tkZ09EMAVrU+TVos8gsFnnmEvEJI4fqrC5cbSYxlIVM4+aV+MseROHLeJgCSndAwmNqtq9v6rA7cL5589tn5TQ8hhAbPtII88uK58etKw15n+bl4ZR9TUw=,iv:TbsToq8OZJNjdnl8kPAJkcbRRrUnZFLXcWPxKOI/owA=,tag:3qxMwN3B0nzY8zpEDpm/Ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
