apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:nX4DG/leRIWHzfOrto3XPeSMijjqmdF0PjoU6J+ZRiPycUDMx5EEqQ==,iv:melttdthrFhLUQo0514vfUNQKyrQ2U9HDl/YY4VnvL0=,tag:k5oYjrr1ETjG5pgWjRJNKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ3B2QVE1S2lSbDFkOEtC
            RjFkVTUrTStOTG1xTlYyMmZHazNOSURjNWdrClJlUkZqYkZYZk5YTURnUVFxOHkv
            K01DNzVhbDd1S3Q5YnVPY0JhdUxZckEKLS0tIG81UFk0K3Fqd2FsczU2ZDhWUVhp
            dHpCSkFGZEtWdmh2Wk5DR2Nhd2FVb3MKtllovuykF/jT7edRKjgpftO7QDl5vC2X
            cvwoUJFJnm8frGdYWLBVVVwDKdQFzkEAIv0+FyDdVBBwO2ejXbuGBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T04:02:19Z"
    mac: ENC[AES256_GCM,data:XrVDm+J86RKRl6c49oyxBXFG8EMsjuC9UOBAWN+QZaJ7uPZsawYUWM9Y8asge3G7twv+wQWZZ56r41SO6dQII9PBKdjdR89/SXr0erboARMQC5LQ3FWOHVLJ29W1zyABKg2FKxoHrfhupnnziF0vIr5Do/pUKfFXFpmbDL6S8DU=,iv:fy1I3Lv2W1ObA4PbMXTT7VpkdSo6MJ7TM/nWhx7v4bQ=,tag:CPTnkuEA+fTMaOk85LOK4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
