apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:fYTIMMdz640C+eL9XqBG8BzI4DH3S9biX8TVV3/wLeopS5s60Oo9+Q==,iv:qjIm8RlUfly9HJoAc96M3Pu8hJCPlILSV8gTHY5OtJo=,tag:Dq4p5lnZ23yjQdZUeRTF2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cqudqwcmj6l32v6thfn4p4rmn9dhar2gcn9u4tp3jcnrf6rvn3usgh0kr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRUt3UW5RcG93ZEVrK1FT
            VENkNUk5aURnV0RMWWFYYkNOdjQ0NEtVeVJFCjBTN0lFZGl3TjJkdCs5cnBNMEhs
            ZWIyRURqZE1lT05YZWxVQ1ZuMEE1UUUKLS0tIHhPTjBoZDlyVmp1NWxQSVhTb0NF
            MVV2VTFMYlJ1a285cGRlTCtsSnljaE0KQHm1mK/Adv87BXCeo6ECMnWBX/NtCteU
            9OS1GuTEIPPQl1Qi8GE617hXoOTr4Xkzl+4QzyawwX2cylGXxn1cLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T00:59:34Z"
    mac: ENC[AES256_GCM,data:YgkmMT+eEjwo0AdKLOVqqVfgwm4Bfg+uGOeZhjsarQ7vRzjjHnmjmwJwAoy09fxNFtWcLD3GJm6SVpztSLsDItOulhdQSmyBdQKN2SRDD2OPBsuMzM+M1JntH46Z1GGxflmkbduNiHOsKLfNGMcbK9/GJTrLqwxR7qPIwbpjWuE=,iv:/mLG10/H5cxKPZxEn11u6/VJBH9R7kYqYaL8qMgY42g=,tag:wt0+MZFEYyAld4xB49MOJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
