---
- name: Tailscale | Set default variables
  ansible.builtin.set_fact:
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_METAL_OAUTH_CLIENT_SECRET') }}"
    tailscale_args: "--hostname={{ inventory_hostname }} --ssh --advertise-connector --advertise-routes=10.0.7.0/24,10.69.0.0/16,10.96.0.0/16 --accept-routes=true --accept-dns=true"
    tailscale_tags:
    - "metal"
    # Optionally, also include:
    tailscale_oauth_ephemeral: false
    tailscale_oauth_preauthorized: true
