---
- name: Prometheus Operator CRDs
  block:
    - name: Prometheus Operator CRDs | Check if Prometheus Operator CRDs HelmChart exists
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: prometheus-operator-crds
        kind: HelmChart
        namespace: kube-system
      register: prometheus_operator_crds_helmchart

    - name: Prometheus Operator CRDs | Wait for Prometheus Operator CRDs to rollout
      when: prometheus_operator_crds_helmchart.resources | count > 0
      kubernetes.core.k8s_info:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: helm-install-prometheus-operator-crds
        kind: Job
        namespace: kube-system
        wait: true
        wait_condition:
          type: Complete
          status: true
        wait_timeout: 360

    # - name: Prometheus Operator CRDs | Patch the Prometheus Operator CRDs HelmChart to unmanage it
    #   when: prometheus_operator_crds_helmchart.resources | count > 0
    #   kubernetes.core.k8s_json_patch:
    #     kubeconfig: /etc/rancher/k3s/k3s.yaml
    #     name: prometheus-operator-crds
    #     kind: HelmChart
    #     namespace: kube-system
    #     patch:
    #       - op: add
    #         path: /metadata/annotations/helmcharts.helm.cattle.io~1unmanaged
    #         value: "true"

    # - name: Prometheus Operator CRDs | Delete the Prometheus Operator CRDs HelmChart CR
    #   when: prometheus_operator_crds_helmchart.resources | count > 0
    #   kubernetes.core.k8s:
    #     kubeconfig: /etc/rancher/k3s/k3s.yaml
    #     name: prometheus-operator-crds
    #     kind: HelmChart
    #     namespace: kube-system
    #     state: absent

    # - name: Prometheus Operator CRDs | Force delete the Prometheus Operator CRDs HelmChart
    #   when: prometheus_operator_crds_helmchart.resources | count > 0
    #   kubernetes.core.k8s:
    #     kubeconfig: /etc/rancher/k3s/k3s.yaml
    #     name: prometheus-operator-crds
    #     kind: HelmChart
    #     namespace: kube-system
    #     state: patched
    #     definition:
    #       metadata:
    #         finalizers: []
