---
- name: Registries
  block:
  - name: Registries | Get Private Registry Password
    ansible.builtin.command: op read "op://Private-Homelab/DockerHub/password"
    register: private_register_password
    delegate_to: localhost
    become: false
    changed_when: false
  - name: Registries | Set Passowrd vars
    ansible.builtin.set_fact:
      private_registry_password: "{{ private_register_password.stdout }}"
  - name: Registries | Generate registries.yaml
    ansible.builtin.copy:
      content: |
        mirrors:
          docker.io:
          gcr.io:
          ghcr.io:
          k8s.gcr.io:
          lscr.io:
          mcr.microsoft.com:
          public.ecr.aws:
          quay.io:
          registry.k8s.io:
        config:
          docker.io:
            auth:
              username: chalkhwang
              password: "{{ private_registry_password }}"
      dest: "{{ k3s_config_file_root }}registries.yaml"
      mode: preserve
