- name: Registries | Get Secret
  ansible.builtin.shell: op read "op://Private-Homelab/DockerHub/password"
  register: docker_password
  delegate_to: localhost
  become: false
- name: Registries | Set Config
  ansible.builtin.copy:
    content: |
      mirrors:
        docker.io:
        gcr.io:
        ghcr.io:
        k8s.gcr.io:
        lscr.io:
        mcr.microsoft.com:
        public.ecr.aws:
        quay.io:
        registry.k8s.io:
      config:
        docker.io:
          auth:
            username: chalkhwang
            password: "{{ docker_password.stdout }}"
            email:
    dest: /etc/rancher/k3s/registries.yaml
    mode: preserve
