---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack

resources:
  - config/
  - prometheus-operator-crds.yaml

helmCharts:
  - name: cert-manager
    version: v1.14.1
    repo: https://charts.jetstack.io
    namespace: monitoring
    releaseName: kube-prometheus
    valuesFile: values.yaml
    includeCRDs: false

